# It would be nice to enable all of these someday
LineLength:
  Enabled: false
MethodLength:
  Enabled: false
CyclomaticComplexity:
  Enabled: false
Documentation:
  Enabled: false

# Either this is a buggy cop, or the cyclomatic complexity 
# is too high for me to see where we're going wrong.
Next:
  Enabled: false
