AllCops:
  Excludes:
    # Excluded because it's still largely code copied out of puppet
    - lib/puppet/type/package.rb

LineLength:
  Enabled: false

MethodLength:
  Enabled: false

Documentation:
  Enabled: false

# Allow the ruby 1.8 hash syntax until we drop ruby 1.8 support
HashSyntax:
  Enabled: false
