# It would be nice to enable all of these someday
LineLength:
  Enabled: false
MethodLength:
  Enabled: false
CyclomaticComplexity:
  Enabled: false
PerceivedComplexity:
  Enabled: false
Documentation:
  Enabled: false

# This cop will make more sense once we reduce
# the complexity further.
Next:
  Enabled: false
