language: ruby
rvm:
  - 1.8.7
  - 1.9.3
  - 2.0.0
  - ruby-head
script: bundle exec rspec spec
env:
  - PUPPET_VERSION="~> 3.0.2"
  - PUPPET_VERSION="~> 3.1.1"
  - PUPPET_VERSION="~> 3.2.1"
matrix:
  # allow_failures:
  #   - rvm: ruby-head
  # include:
  #   - rvm: 1.8.7
  #     env: PUPPET_VERSION="~> 2.7.21"
  exclude:
    - rvm: 2.0.0
      env: PUPPET_VERSION="~> 3.0.2"
    - rvm: 2.0.0
      env: PUPPET_VERSION="~> 3.1.1"
    - rvm: ruby-head
      env: PUPPET_VERSION="~> 3.0.2"
    - rvm: ruby-head
      env: PUPPET_VERSION="~> 3.1.1"
