language: ruby
rvm:
  # This should match up with what you find here:
  # https://packages.gentoo.org/package/dev-lang/ruby
  - 1.9.3
  - 2.0.0
  - 2.1.2
  # - 2.2.0
  - ruby-head

script:
  - bundle exec rspec --color --format documentation
  - bundle exec rubocop

env:
  - PUPPET_VERSION="~> 3.5.1"
  - PUPPET_VERSION="~> 3.6.2"

matrix:
  allow_failures:
    # - rvm: 2.2.0
    - rvm: ruby-head

  # exclude:
  #   - rvm: 2.2.0
  #     env: PUPPET_VERSION="~> 3.5.0"
