language: ruby
rvm:
  - ruby-head
  - 1.9.3
script: bundle exec rspec spec
env:
  - PUPPET_VERSION="~> 3.0.2"
  - PUPPET_VERSION="~> 3.1.1"
matrix:
  allow_failures:
    - rvm: ruby-head
  # include:
  #   - rvm: 1.8.7
  #     env: PUPPET_VERSION="~> 2.7.21"