language: ruby
rvm:
  - 2.2.6
  - 2.3.3
  - 2.4.0
  - ruby-head

sudo: false
script:
  - bundle exec rspec --color --format documentation

env:
  - PUPPET_VERSION="~> 4.8.0"
  - PUPPET_VERSION="~> 4.9.0"
  - PUPPET_VERSION="~> 4.10.0"
  - PUPPET_VERSION="~> 5.0.0"
  - PUPPET_VERSION="~> 5.1.0"

matrix:
  allow_failures:
    - rvm: ruby-head
