language: ruby
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.5
  - 2.2.0
  - ruby-head

sudo: false
script:
  - bundle exec rspec --color --format documentation

env:
  - PUPPET_VERSION="~> 3.5.1"
  - PUPPET_VERSION="~> 3.6.2"
  - PUPPET_VERSION="~> 3.7.5"
  - PUPPET_VERSION="~> 4.0.0"
  - PUPPET_VERSION="~> 4.0.0" STRICT_VARIABLES=yes

matrix:
  allow_failures:
    - rvm: ruby-head

  exclude:
     - rvm: 2.2.0
       env: PUPPET_VERSION="~> 3.5.1"
     - rvm: 2.2.0
       env: PUPPET_VERSION="~> 3.6.2"
     - rvm: 2.2.0
       env: PUPPET_VERSION="~> 3.7.5"
