language: ruby
rvm:
  - 1.9.3
  - 2.0.0
  - ruby-head
script:
  - bundle exec facter
  - bundle exec rspec --color --format documentation
  - bundle exec rubocop
env:
  - PUPPET_VERSION="~> 3.0.2"
  - PUPPET_VERSION="~> 3.1.1"
  - PUPPET_VERSION="~> 3.2.1"
  - PUPPET_VERSION="~> 3.3.0"
matrix:
  allow_failures:
    - rvm: ruby-head
  include:
    - rvm: 1.8.7
      env: PUPPET_VERSION="~> 3.0.2"
      gemfile: Gemfile18
      script: bundle exec rspec
    - rvm: 1.8.7
      env: PUPPET_VERSION="~> 3.1.1"
      gemfile: Gemfile18
      script: bundle exec rspec
    - rvm: 1.8.7
      env: PUPPET_VERSION="~> 3.2.1"
      gemfile: Gemfile18
      script: bundle exec rspec
    - rvm: 1.8.7
      env: PUPPET_VERSION="~> 3.3.0"
      gemfile: Gemfile18
      script: bundle exec rspec
  exclude:
    - rvm: 2.0.0
      env: PUPPET_VERSION="~> 3.0.2"
    - rvm: 2.0.0
      env: PUPPET_VERSION="~> 3.1.1"
    - rvm: ruby-head
      env: PUPPET_VERSION="~> 3.0.2"
    - rvm: ruby-head
      env: PUPPET_VERSION="~> 3.1.1"
