language: ruby
rvm:
  - 2.0.0
  - 2.1.5
  - 2.2.6
  - 2.3.3
  - 2.4.0
  - ruby-head

sudo: false
script:
  - bundle exec rspec --color --format documentation

env:
  - PUPPET_VERSION="~> 3.5.1"
  - PUPPET_VERSION="~> 3.6.2"
  - PUPPET_VERSION="~> 3.7.5"
  - PUPPET_VERSION="~> 4.0.0"
  - PUPPET_VERSION="~> 4.1.0"
  - PUPPET_VERSION="~> 4.2.0"
  - PUPPET_VERSION="~> 4.3.0"
  - PUPPET_VERSION="~> 4.4.0"
  - PUPPET_VERSION="~> 4.5.0"
  - PUPPET_VERSION="~> 4.6.0"
  - PUPPET_VERSION="~> 4.7.0"
  - PUPPET_VERSION="~> 4.8.0"

  # Alternative operating modes
  # Only test latest version
  - PUPPET_VERSION="~> 4.8.0" STRICT_VARIABLES=yes

matrix:
  allow_failures:
    - rvm: ruby-head

  exclude:
     - rvm: ruby-head
       env: PUPPET_VERSION="~> 3.5.1"
     - rvm: ruby-head
       env: PUPPET_VERSION="~> 3.6.2"
     - rvm: ruby-head
       env: PUPPET_VERSION="~> 3.7.5"

     - rvm: 2.2.6
       env: PUPPET_VERSION="~> 3.5.1"
     - rvm: 2.2.6
       env: PUPPET_VERSION="~> 3.6.2"
     - rvm: 2.2.6
       env: PUPPET_VERSION="~> 3.7.5"

     - rvm: 2.3.3
       env: PUPPET_VERSION="~> 3.5.1"
     - rvm: 2.3.3
       env: PUPPET_VERSION="~> 3.6.2"
     - rvm: 2.3.3
       env: PUPPET_VERSION="~> 3.7.5"

     - rvm: 2.4.0
       env: PUPPET_VERSION="~> 3.5.1"
     - rvm: 2.4.0
       env: PUPPET_VERSION="~> 3.6.2"
     - rvm: 2.4.0
       env: PUPPET_VERSION="~> 3.7.5"
